<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DevolveFacill.Workers</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevolveFacill.Core\DevolveFacill.Core.csproj" />
    <ProjectReference Include="..\DevolveFacill.Infrastructure\DevolveFacill.Infrastructure.csproj" />
    <ProjectReference Include="..\DevolveFacill.Adapters\DevolveFacill.Adapters.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.3" />
    <PackageReference Include="MailKit" Version="4.3.0" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
  </ItemGroup>
</Project>
